language: python
python:
  - "2.7"

language: node_js
node_js:
  - "node"

install:
  - pip install -r requirements.txt

cache:
  directories:
    - "node_modules"

script:
  - flake8 ssb
  - npm run lint