language: python
python:
  - "3.7.0"
node_js:
  - "lts/*"
addons:
  postgresql: "9.6"

dist: xenial
sudo: true

install:
  - npm install
  - pip install -r requirements.txt

cache:
  directories:
    - "node_modules"

script:
  - flake8 ssb
  - npm run lint