# Generated by Django 2.2.4 on 2019-08-24 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poses', '0004_auto_20190824_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_order', models.PositiveIntegerField(db_index=True)),
                ('pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.Pose')),
            ],
            options={
                'ordering': ['-pose_order'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('poses', models.ManyToManyField(related_name='multi_pose_flow', through='sequences.OrderedPose', to='poses.Pose')),
            ],
        ),
        migrations.AddField(
            model_name='orderedpose',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequences.Sequence'),
        ),
    ]
