# Generated by Django 2.2.4 on 2019-08-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderedpose',
            unique_together={('sequence', 'pose_order')},
        ),
    ]
