# Generated by Django 2.2.4 on 2019-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_auto_20190826_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='creation_time',
            field=models.DateField(auto_now=True),
        ),
    ]
