# Generated by Django 2.2.4 on 2019-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0003_sequence_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedpose',
            name='breath_override',
            field=models.IntegerField(choices=[(0, 'Inhale'), (1, 'Exhale')], default=1),
            preserve_default=False,
        ),
    ]
