# Generated by Django 3.0.1 on 2020-01-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0004_orderedpose_breath_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedpose',
            options={'ordering': ['pose_order']},
        ),
        migrations.AddField(
            model_name='orderedpose',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
