# Generated by Django 3.0.1 on 2019-12-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0005_auto_20190828_1930'),
        ('sequences', '0004_orderedpose_breath_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('is_pose', models.BooleanField(default=False)),
                ('creation_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedSequenceElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='orderedpose',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='orderedpose',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='OrderedSequenceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_order', models.PositiveIntegerField(db_index=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequences.OrderedSequenceElement')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequences.Sequence')),
            ],
            options={
                'ordering': ['pose_order'],
                'unique_together': {('sequence', 'pose_order')},
            },
        ),
        migrations.CreateModel(
            name='OrderedFlowPose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_order', models.PositiveIntegerField(db_index=True)),
                ('breath_override', models.IntegerField(choices=[(0, 'Inhale'), (1, 'Exhale')])),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequences.Flow')),
                ('pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.Pose')),
            ],
            options={
                'ordering': ['pose_order'],
                'unique_together': {('flow', 'pose_order')},
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='poses',
            field=models.ManyToManyField(related_name='multi_pose_flow', through='sequences.OrderedFlowPose', to='poses.Pose'),
        ),
        migrations.RemoveField(
            model_name='orderedpose',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderedpose',
            name='pose_order',
        ),
        migrations.RemoveField(
            model_name='orderedpose',
            name='sequence',
        ),
        migrations.AddField(
            model_name='orderedpose',
            name='orderedsequenceelement_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sequences.OrderedSequenceElement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequence',
            name='poses',
            field=models.ManyToManyField(related_name='multi_pose_sequence', through='sequences.OrderedSequenceBase', to='sequences.OrderedSequenceElement'),
        ),
        migrations.CreateModel(
            name='OrderedFlow',
            fields=[
                ('orderedsequenceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sequences.OrderedSequenceElement')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequences.Flow')),
            ],
            bases=('sequences.orderedsequenceelement',),
        ),
    ]
