# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def initialize_breath_choices(apps, schema_editor):
    Breath = apps.get_model("poses", "Breath")

    for choice in (0, 1):
        Breath.objects.get_or_create(direction=choice)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Breath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(choices=[(0, b'Inhale'), (1, b'Exhale')])),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_type', models.IntegerField(choices=[(0, b'Stretch'), (1, b'Strengthen'), (2, b'Warm')])),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.BodyPart')),
            ],
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('spinal_classification', models.IntegerField(choices=[(0, b'Twist'), (1, b'Backbend'), (2, b'Lateral Bend'), (3, b'Forward Bend'), (4, b'Extension')])),
                ('position_classification', models.IntegerField(choices=[(0, b'Supine'), (1, b'Kneeling'), (2, b'Prone'), (3, b'Standing'), (4, b'Seated')])),
                ('challenge_level', models.IntegerField(choices=[(0, b'Gentle'), (1, b'Moderate'), (2, b'Advanced')])),
                ('benefits', models.ManyToManyField(related_name='pose_benefits', to='poses.Effect')),
                ('breath', models.ManyToManyField(default=1, to='poses.Breath')),
                ('compensation', models.ManyToManyField(related_name='pose_compensation_requirements', to='poses.Effect')),
                ('preparation', models.ManyToManyField(related_name='pose_prepartion_requirements', to='poses.Effect')),
            ],
        ),
        migrations.RunPython(initialize_breath_choices)
    ]
