# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def initialize_breath_choices(apps, schema_editor):
    Breath = apps.get_model("poses", "Breath")

    for choice in (0, 1):
        Breath.objects.get_or_create(direction=choice)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(choices=[(0, b'Inhale'), (1, b'Exhale')])),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_type', models.IntegerField(choices=[(0, b'Stretch'), (1, b'Strengthen'), (2, b'Warm')])),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.BodyPart')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedPose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_order', models.PositiveIntegerField(db_index=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.Flow')),
            ],
            options={
                'ordering': ['pose_order'],
            },
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('english_name', models.CharField(max_length=128, unique=True)),
                ('sanskrit_name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('spinal_classification', models.IntegerField(choices=[(0, b'Twist'), (1, b'Backbend'), (2, b'Lateral Bend'), (3, b'Forward Bend'), (4, b'Extension')])),
                ('position_classification', models.IntegerField(choices=[(0, b'Supine'), (1, b'Kneeling'), (2, b'Prone'), (3, b'Standing'), (4, b'Seated')])),
                ('challenge_level', models.IntegerField(choices=[(0, b'Gentle'), (1, b'Moderate'), (2, b'Intermediate'), (3, b'Advanced')])),
                ('benefits', models.ManyToManyField(related_name='pose_benefits', to='poses.Effect')),
                ('breath', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poses.Breath')),
                ('compensation', models.ManyToManyField(blank=True, related_name='pose_compensation_requirements', to='poses.Effect')),
                ('preparation', models.ManyToManyField(blank=True, related_name='pose_prepartion_requirements', to='poses.Effect')),
            ],
        ),
        migrations.AddField(
            model_name='orderedpose',
            name='pose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.Pose'),
        ),
        migrations.AddField(
            model_name='flow',
            name='poses',
            field=models.ManyToManyField(related_name='multi_pose_flow', through='poses.OrderedPose', to='poses.Pose'),
        ),
        migrations.AlterUniqueTogether(
            name='effect',
            unique_together=set([('body_part', 'activation_type')]),
        ),
        migrations.RunPython(initialize_breath_choices),
    ]
