# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_type', models.IntegerField(choices=[(1, b'Stretch'), (2, b'Strengthen'), (3, b'Warm')])),
            ],
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('spinal_classification', models.IntegerField(choices=[(1, b'Twist'), (2, b'Backbend'), (3, b'Lateral Bend'), (4, b'Forward Bend'), (5, b'Extension')])),
                ('position_classification', models.IntegerField(choices=[(1, b'Supine'), (2, b'Kneeling'), (3, b'Prone'), (4, b'Standing'), (5, b'Seated')])),
                ('challenge_level', models.IntegerField(choices=[(1, b'Gentle'), (2, b'Moderate'), (3, b'Advanced')])),
                ('benefits', models.ManyToManyField(to='poses.Benefit')),
            ],
        ),
        migrations.AddField(
            model_name='benefit',
            name='body_parts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.BodyPart'),
        ),
    ]
