# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pose',
            old_name='name',
            new_name='english_name',
        ),
        migrations.AddField(
            model_name='pose',
            name='sanskrit_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pose',
            name='compensation',
            field=models.ManyToManyField(blank=True, related_name='pose_compensation_requirements', to='poses.Effect'),
        ),
        migrations.AlterField(
            model_name='pose',
            name='preparation',
            field=models.ManyToManyField(blank=True, related_name='pose_prepartion_requirements', to='poses.Effect'),
        ),
    ]
