# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefit',
            old_name='body_parts',
            new_name='body_part',
        ),
        migrations.AlterField(
            model_name='pose',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='poses.Benefit'),
        ),
    ]
