# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoseVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('challenge_level', models.IntegerField(choices=[(0, b'Gentle'), (1, b'Moderate'), (2, b'Intermediate'), (3, b'Advanced')])),
                ('arm_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poses.ArmVariation')),
                ('benefits', models.ManyToManyField(blank=True, related_name='variation_benefits', to='poses.Effect')),
                ('compensation', models.ManyToManyField(blank=True, related_name='variation_compensation_requirements', to='poses.Effect')),
                ('leg_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poses.LegVariation')),
                ('parent_pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poses.Pose')),
                ('preparation', models.ManyToManyField(blank=True, related_name='variation_prepartion_requirements', to='poses.Effect')),
            ],
        ),
        migrations.AlterModelOptions(
            name='orderedpose',
            options={'ordering': ['-pose_order']},
        ),
    ]
