# Generated by Django 2.2.4 on 2019-08-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0002_auto_20170216_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breath',
            name='direction',
            field=models.IntegerField(choices=[(0, 'Inhale'), (1, 'Exhale')]),
        ),
        migrations.AlterField(
            model_name='effect',
            name='activation_type',
            field=models.IntegerField(choices=[(0, 'Stretch'), (1, 'Strengthen'), (2, 'Warm')]),
        ),
        migrations.AlterField(
            model_name='pose',
            name='challenge_level',
            field=models.IntegerField(choices=[(0, 'Gentle'), (1, 'Moderate'), (2, 'Intermediate'), (3, 'Advanced')]),
        ),
        migrations.AlterField(
            model_name='pose',
            name='position_classification',
            field=models.IntegerField(choices=[(0, 'Supine'), (1, 'Kneeling'), (2, 'Prone'), (3, 'Standing'), (4, 'Seated')]),
        ),
        migrations.AlterField(
            model_name='pose',
            name='spinal_classification',
            field=models.IntegerField(choices=[(0, 'Twist'), (1, 'Backbend'), (2, 'Lateral Bend'), (3, 'Forward Bend'), (4, 'Extension')]),
        ),
        migrations.AlterField(
            model_name='posevariation',
            name='challenge_level',
            field=models.IntegerField(choices=[(0, 'Gentle'), (1, 'Moderate'), (2, 'Intermediate'), (3, 'Advanced')]),
        ),
    ]
