# Generated by Django 2.2.4 on 2019-08-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0003_auto_20190820_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedpose',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='orderedpose',
            name='pose',
        ),
        migrations.DeleteModel(
            name='Flow',
        ),
        migrations.DeleteModel(
            name='OrderedPose',
        ),
    ]
