# Generated by Django 2.2.4 on 2019-08-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0004_auto_20190824_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='breath',
            field=models.IntegerField(choices=[(0, 'Inhale'), (1, 'Exhale'), (2, 'Either')]),
        ),
        migrations.DeleteModel(
            name='Breath',
        ),
    ]
