# Generated by Django 3.0.1 on 2020-01-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0005_auto_20190828_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='is_flow',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
